version: '3.7'

services:
    server:
        image: flacatus/server
        container_name: server
        tty: true # Needed to ensure container doesn't self terminate
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            MONGO_URI: mongodb://mongodb:27017/api
            PORT: 3000
        ports: ['3000:3000'] # host:container
        depends_on:
            - mongodb
        networks:
            - quarkus

    mongodb:
        image: mongo  #:latest
        #environment:
        #    MONGO_INITDB_ROOT_USERNAME: root
        #    MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - quarkus
    
    # https://dev.to/sonyarianto/how-to-spin-mongodb-server-with-docker-and-docker-compose-2lef
    # https://www.thepolyglotdeveloper.com/2019/01/getting-started-mongodb-docker-container-deployment/

volumes:
  mongodb_data_container:

networks:
    quarkus:
        driver: bridge
