version: '3.7'

services:
    front:
        image: cookiespoc/front
        container_name: front
        tty: true # Needed to ensure container doesn't self terminate
        build:
            context: ./front
            dockerfile: Dockerfile
        environment:
            BACK_URI: server:4000
        ports: ['5000:5000'] # host:container
        depends_on:
            - server
        networks:
            - quarkus

    server:
        image: flacatus/server
        container_name: server
        tty: true # Needed to ensure container doesn't self terminate
        build:
            context: ./sample_api_server
            dockerfile: Dockerfile
        environment:
            MONGO_URI: mongodb://mongodb:27017/api
            PORT: 4000
        ports: ['4000:4000'] # host:container
        depends_on:
            - mongodb
        networks:
            - quarkus

    mongodb:
        image: mongo  #:latest
        #environment:
        #    MONGO_INITDB_ROOT_USERNAME: root
        #    MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
            - "27017:27017"
        volumes:
            - mongodb_data_container:/data/db
        networks:
            - quarkus

volumes:
  mongodb_data_container:
              
networks:
    quarkus:
        driver: bridge
